### PR TITLE
forward compatibility changes

### PR DESCRIPTION
**Pull request by pelikhan**
Required changes to support next iteration of the microbit editor.

### CODE REVIEW

**Comment by pelikhan** [comment]
@Gadgetoid

**Comment by Gadgetoid** [comment]
I attempted to use the .travis.yml you linked as one of my first attempts to get CI up and running, but it wouldn't work- at the time the "pxt build --cloud" still relied on having all of the local dependencies satisfied. I'm willing to have another crack at it when I've got time since it's pretty clear my current setup isn't perfect.

Thank you for these tweaks- is there any documentation that explains why they're necessary? I'm guessing the `PXT_CREATE_BUFFER` macro is for the sake of convenience, and the main change is that `ManagedBuffer` requires both a data and length parameter?

**Comment by pelikhan** [comment]
ManagedBuffer is deprecated in v1....

_____________________________

**Comment by Gadgetoid** [comment]
Merged, thank you!

Does this necessitate a PXT bump? - I'm not certain how the package is pulled in from GitHub.

**Comment by pelikhan** [comment]
Yes please bump. The cloud only looks at releases.

**Comment by pelikhan** [comment]
@Gadgetoid could you bump to pick up those changes?

**Pull request merged**
